#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
batch_test.py — Parallel batch evaluation harness for the Text-to-SQL agent.

Reads questions from an Excel column, runs every question through the full
DRGC pipeline capturing all intermediate steps and timing, then writes an
enriched Excel file with one row per question.

Usage
─────
    # Minimal (auto-discovers the first text column with 'question' in its name)
    python batch_test.py questions.xlsx

    # Explicit column name
    python batch_test.py questions.xlsx --col "Question"

    # Parallelism + output path
    python batch_test.py questions.xlsx --col "Question" --workers 10 --out results.xlsx

    # Limit to first N rows (smoke test)
    python batch_test.py questions.xlsx --col "Question" --limit 20

    # Retry failed rows from a previous run
    python batch_test.py results.xlsx --col "Question" --retry-errors

Options
───────
    --col           Column name that contains the questions  [default: auto-detect]
    --workers       Number of parallel threads               [default: 5]
    --out           Output Excel file path                   [default: <input>_results_<ts>.xlsx]
    --limit         Only run the first N questions           [default: all]
    --retry-errors  Re-run only rows where status == 'error' in a previous result file
    --log-level     Logging verbosity: DEBUG | INFO | WARNING | ERROR  [default: WARNING]
    --no-warmup     Skip the explicit cache-warmup barrier (first queries may be slower)

Output columns
──────────────
    question_no          Row index (1-based)
    question             Original question text
    status               success | error | clarification | non_data
    intent               Classified routing intent
    plan                 Logical decomposition plan
    schema_categories    Schema category groups selected by planner
    few_shot_count       Number of few-shot examples injected
    sql_query            Final SQL query (after filter corrections)
    filter_corrections   Summary of filter value corrections made
    validation_passed    Whether rule-based SQL validation passed
    validation_issues    Validation failure messages (if any)
    sql_corrections      Number of SQL self-correction iterations
    execution_time_ms    SQL execution time (database only)
    result_row_count     Number of rows returned by the query
    llm_answer           Natural-language answer generated by the responder
    total_time_s         End-to-end wall-clock time in seconds
    error                Error message (if status == 'error')
    steps_timeline       Human-readable step-by-step timeline
    steps_json           Machine-readable JSON of all steps (for programmatic use)
"""

from __future__ import annotations

# ─────────────────────────────────────────────────────────────────────────────
# Silence EVERYTHING before any agent import
# ─────────────────────────────────────────────────────────────────────────────
import warnings
warnings.filterwarnings("ignore")          # Python DeprecationWarning, etc.

import logging
import os
import sys

# Suppress standard-library loggers used by LangChain / httpx / openai / etc.
for _name in ("httpx", "httpcore", "openai", "langchain", "langchain_core",
              "langchain_groq", "langchain_openai", "chromadb",
              "sentence_transformers", "transformers", "torch",
              "urllib3", "requests", "asyncio", "langgraph", "groq"):
    logging.getLogger(_name).setLevel(logging.CRITICAL)
logging.disable(logging.WARNING)

# Remove loguru's default stderr sink immediately — we will add a FILE sink only.
from loguru import logger as _loguru_logger
_loguru_logger.remove()

# ─────────────────────────────────────────────────────────────────────────────
# Standard-library imports
# ─────────────────────────────────────────────────────────────────────────────
import argparse
import json
import threading
import time
import traceback
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pandas as pd
from tqdm import tqdm

# ─────────────────────────────────────────────────────────────────────────────
# Parse CLI args early so we know --log-file before heavy imports
# ─────────────────────────────────────────────────────────────────────────────
_parser = argparse.ArgumentParser(
    description="Parallel batch evaluation of the Text-to-SQL agent",
    formatter_class=argparse.RawDescriptionHelpFormatter,
    epilog=__doc__,
)
_parser.add_argument("input",          help="Input Excel file path")
_parser.add_argument("--col",          help="Column name containing questions (auto-detected if omitted)")
_parser.add_argument("--workers",      type=int, default=5, help="Parallel threads (default: 5)")
_parser.add_argument("--out",          help="Output Excel path (auto-named if omitted)")
_parser.add_argument("--limit",        type=int, default=None, help="Only run the first N questions")
_parser.add_argument("--retry-errors", action="store_true",
                     help="Re-run only rows with status=='error' from a previous result file")
_parser.add_argument("--log-file",     help="Write all agent logs here (default: batch_test_<ts>.log)")
_parser.add_argument("--no-warmup",    action="store_true",
                     help="Skip the startup cache-warmup barrier")
_args = _parser.parse_args()

# ── Wire loguru to file only (zero console output from agent) ─────────────────
_ts_str   = datetime.now().strftime("%Y%m%d_%H%M%S")
_log_path = _args.log_file or f"batch_test_{_ts_str}.log"
_loguru_logger.add(
    _log_path,
    level="DEBUG",
    encoding="utf-8",
    rotation="100 MB",
    format="{time:YYYY-MM-DD HH:mm:ss} | {level:<8} | {name}:{line} | {message}",
)

# ── Load heavy agent modules ──────────────────────────────────────────────────
_load_bar = tqdm(
    total=1, desc="Loading agent",
    bar_format="{desc}: {elapsed}",
    leave=False, file=sys.stdout, dynamic_ncols=True,
)
_t0_import = time.time()

from graph import stream_agent_steps, NODE_LABELS                    # noqa: E402
from agents.filter_resolver import initialize_value_cache, _CACHE_READY_EVENT  # noqa: E402
from core.database import db_manager                                 # noqa: E402

_load_bar.close()
_import_ms = (time.time() - _t0_import) * 1000
tqdm.write(f"✅  Modules loaded  ({_import_ms:.0f} ms)  │  Logs → {_log_path}")


# ─────────────────────────────────────────────────────────────────────────────
# One-time startup barrier
# ─────────────────────────────────────────────────────────────────────────────

def _warmup() -> None:
    """Wait for filter-resolver value cache to be ready."""
    if _CACHE_READY_EVENT.is_set():
        tqdm.write("✅  Value cache already warm")
        return
    bar = tqdm(
        total=1, desc="Cache warmup",
        bar_format="{desc}: {elapsed}",
        leave=False, file=sys.stdout, dynamic_ncols=True,
    )
    _t = time.time()
    _CACHE_READY_EVENT.wait()
    bar.close()
    tqdm.write(f"✅  Value cache ready  ({(time.time()-_t)*1000:.0f} ms)")


# ─────────────────────────────────────────────────────────────────────────────
# Per-question runner
# ─────────────────────────────────────────────────────────────────────────────

def _run_one(row_no: int, question: str) -> Dict:
    """
    Execute one question through the full pipeline and return a flat result dict.

    Uses stream_agent_steps() so we can capture the per-node timeline with
    individual timing, while still collecting the complete final state.
    """
    result: Dict = {
        "question_no":         row_no,
        "question":            question,
        "status":              "error",
        "intent":              "",
        "plan":                "",
        "schema_categories":   "",
        "few_shot_count":      0,
        "sql_query":           "",
        "filter_corrections":  "",
        "validation_passed":   "",
        "validation_issues":   "",
        "sql_corrections":     0,
        "execution_time_ms":   "",
        "result_row_count":    "",
        "result_data_json":    "",
        "llm_answer":          "",
        "total_time_s":        "",
        "error":               "",
        "steps_timeline":      "",
        "steps_json":          "",
    }

    steps: List[Dict] = []
    wall_start = time.time()
    prev_ts = wall_start

    try:
        final_state: Optional[Dict] = None

        for event in stream_agent_steps(question, conversation_history=[]):
            now = time.time()
            if event["type"] == "step":
                node  = event["node"]
                label = event["label"]
                delta_ms = (now - prev_ts) * 1000
                prev_ts  = now

                # Collect a compact summary of what this node changed
                output = event.get("output") or {}
                changed_keys = [k for k in output if output[k] is not None
                                and k not in ("messages", "start_time")]

                steps.append({
                    "node":       node,
                    "label":      label,
                    "delta_ms":   round(delta_ms, 1),
                    "changed":    changed_keys,
                    "output_summary": _summarise_output(node, output),
                })

            elif event["type"] == "final":
                final_state = event["state"]

        wall_s = time.time() - wall_start

        if final_state is None:
            result["error"] = "Graph returned no final state"
            return result

        # ── Unpack final state ───────────────────────────────────────────────
        intent = final_state.get("intent") or ""
        error  = final_state.get("error")  or ""

        # Determine high-level status
        if error and not final_state.get("nl_response"):
            status = "error"
        elif final_state.get("needs_clarification"):
            status = "clarification"
        elif intent and intent not in ("data_query", "follow_up", "correction"):
            status = "non_data"
        else:
            status = "success"

        # Filter correction summary
        filter_log = final_state.get("filter_log") or []
        corrections = [
            f"{e['column']}='{e['sql_value']}' → {e.get('matched_column', e['column'])}='{e['db_match']}'"
            for e in filter_log
            if e.get("action") in ("corrected", "column_corrected", "business_rule")
        ]

        # Validation
        val_issues = final_state.get("validation_issues") or []

        # Result rows — normalise to list of dicts and keep all rows
        q_result = final_state.get("query_result")
        row_count = len(q_result) if isinstance(q_result, list) else ""

        # Serialise every row to JSON for storage
        result_data_json = ""
        if isinstance(q_result, list) and len(q_result) > 0:
            try:
                first = q_result[0]
                if isinstance(first, dict):
                    all_dicts = q_result
                elif hasattr(first, "_mapping"):
                    all_dicts = [dict(r._mapping) for r in q_result]
                elif hasattr(first, "_asdict"):
                    all_dicts = [r._asdict() for r in q_result]
                else:
                    all_dicts = [str(r) for r in q_result]
                result_data_json = json.dumps(all_dicts, ensure_ascii=False,
                                              default=str)
            except Exception as _e:
                result_data_json = f"[serialisation error: {_e}]"

        # Steps: human-readable timeline
        steps_tl = _build_timeline(steps, wall_s)

        result.update({
            "status":              status,
            "intent":              intent,
            "plan":                (final_state.get("plan") or "").replace("\n", " | "),
            "schema_categories":   ", ".join(final_state.get("relevant_schema_categories") or []),
            "few_shot_count":      len(final_state.get("few_shot_examples") or []),
            "sql_query":           final_state.get("sql_query") or "",
            "filter_corrections":  "; ".join(corrections) if corrections else "none",
            "validation_passed":   str(final_state.get("validation_passed") or ""),
            "validation_issues":   " | ".join(val_issues),
            "sql_corrections":     final_state.get("iterations") or 0,
            "execution_time_ms":   round(final_state.get("execution_time_ms") or 0, 1),
            "result_row_count":    row_count,
            "result_data_json":    result_data_json,
            "llm_answer":          final_state.get("nl_response")
                                   or final_state.get("direct_response") or "",
            "total_time_s":        round(wall_s, 2),
            "error":               error,
            "steps_timeline":      steps_tl,
            "steps_json":          json.dumps(steps, ensure_ascii=False),
        })

    except Exception as exc:
        result["error"]        = f"{type(exc).__name__}: {exc}"
        result["total_time_s"] = round(time.time() - wall_start, 2)
        result["steps_json"]   = json.dumps(steps, ensure_ascii=False)
        _loguru_logger.error(f"[Q#{row_no}] Unhandled error: {exc}\n{traceback.format_exc()}")

    return result


def _summarise_output(node: str, output: Dict) -> str:
    """Compact human-readable summary of what a node wrote to state."""
    if not output:
        return ""
    snippets: List[str] = []

    if node == "interaction":
        if output.get("intent"):
            snippets.append(f"intent={output['intent']}")
        rewritten = output.get("question")
        if rewritten:
            snippets.append(f"rewritten_q={rewritten[:60]!r}")

    elif node == "planner":
        if output.get("plan"):
            first_line = (output["plan"] or "").split("\n")[0][:80]
            snippets.append(f"plan={first_line!r}")
        cats = output.get("relevant_schema_categories")
        if cats:
            snippets.append(f"categories={cats}")

    elif node == "context_builder":
        n_ex = len(output.get("few_shot_examples") or [])
        if n_ex:
            snippets.append(f"{n_ex} few-shot example(s)")
        if output.get("schema_context"):
            snippets.append("schema_context ready")

    elif node == "generator":
        sql = output.get("sql_query") or ""
        if sql:
            snippets.append(f"sql={sql[:80].replace(chr(10), ' ')!r}")

    elif node == "filter_resolver":
        fl = output.get("filter_log") or []
        if fl:
            actions = [e.get("action", "?") for e in fl]
            snippets.append(f"filters={actions}")
        if output.get("needs_clarification"):
            snippets.append("⚠ needs_clarification")

    elif node == "sql_validator":
        snippets.append(
            "PASSED" if output.get("validation_passed") else
            f"FAILED: {output.get('validation_issues', [])}"
        )

    elif node == "executor":
        if output.get("error"):
            snippets.append(f"ERROR: {str(output['error'])[:80]}")
        elif output.get("result_preview"):
            snippets.append(f"rows={output.get('result_preview', '')[:60]!r}")

    elif node == "reflector":
        sql = output.get("sql_query") or ""
        if sql:
            snippets.append(f"fixed_sql={sql[:60].replace(chr(10), ' ')!r}")

    elif node == "responder":
        ans = output.get("nl_response") or ""
        if ans:
            snippets.append(f"answer={ans[:80]!r}")

    return "; ".join(snippets)


def _build_timeline(steps: List[Dict], total_s: float) -> str:
    """Render a compact human-readable step timeline string."""
    lines: List[str] = []
    for i, s in enumerate(steps, 1):
        summary = s["output_summary"]
        detail  = f" → {summary}" if summary else ""
        lines.append(
            f"Step {i:>2}  [{s['delta_ms']:>7.1f} ms]  {s['label']}{detail}"
        )
    lines.append(f"{'─'*60}")
    lines.append(f"Total: {total_s:.2f} s")
    return "\n".join(lines)





# ─────────────────────────────────────────────────────────────────────────────
# Excel I/O helpers
# ─────────────────────────────────────────────────────────────────────────────

def _load_questions(
    xlsx_path: str,
    col: Optional[str],
    limit: Optional[int],
    retry_errors: bool,
) -> Tuple[List[Tuple[int, str]], pd.DataFrame]:
    """Load questions from Excel.  Returns [(row_no, question), ...] and the raw df."""
    df = pd.read_excel(xlsx_path, engine="openpyxl")

    # Auto-detect question column
    if col is None:
        candidates = [c for c in df.columns
                      if "question" in str(c).lower() or "query" in str(c).lower()]
        if candidates:
            col = candidates[0]
        elif len(df.columns) == 1:
            col = df.columns[0]
        else:
            raise ValueError(
                f"Cannot auto-detect question column in {xlsx_path}. "
                f"Available columns: {list(df.columns)}. "
                "Use --col to specify."
            )
    else:
        if col not in df.columns:
            raise ValueError(
                f"Column '{col}' not found. Available: {list(df.columns)}"
            )

    tqdm.write(f"📄  Input file  : {xlsx_path}")
    tqdm.write(f"🔑  Question col: '{col}'  ({len(df)} total rows)")

    # Filter to error-only rows for retry mode
    if retry_errors and "status" in df.columns:
        df = df[df["status"] == "error"].copy()
        tqdm.write(f"♻️   Retry mode  : {len(df)} error row(s) to re-run")

    # Drop blank questions
    df = df[df[col].astype(str).str.strip().ne("") & df[col].notna()].copy()
    df.reset_index(drop=True, inplace=True)

    if limit is not None:
        df = df.head(limit)
        tqdm.write(f"🔢  Limit        : first {limit} question(s)")

    pairs = [(i + 1, str(q).strip()) for i, q in enumerate(df[col])]
    tqdm.write(f"📊  Will run     : {len(pairs)} question(s)")
    return pairs, df


_OUTPUT_COLUMNS = [
    "question_no", "question", "status", "intent",
    "plan", "schema_categories", "few_shot_count",
    "sql_query", "filter_corrections",
    "validation_passed", "validation_issues", "sql_corrections",
    "execution_time_ms", "result_row_count", "result_data_json",
    "llm_answer", "total_time_s", "error",
    "steps_timeline", "steps_json",
]


def _save_results(results: List[Dict], out_path: str) -> None:
    """Save results to Excel with auto-column widths and frozen header."""
    out_df = pd.DataFrame(results, columns=_OUTPUT_COLUMNS)

    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        out_df.to_excel(writer, index=False, sheet_name="Results")

        ws = writer.sheets["Results"]

        # Freeze header row
        ws.freeze_panes = "A2"

        # Auto-fit column widths (capped)
        _COL_MAX = {
            "question":         60,
            "plan":             80,
            "sql_query":        90,
            "llm_answer":       80,
            "steps_timeline":   100,
            "steps_json":       50,
            "result_data_json": 60,
            "filter_corrections": 60,
            "validation_issues":  60,
        }
        for col_idx, col_name in enumerate(out_df.columns, start=1):
            max_len = max(
                len(str(col_name)),
                out_df[col_name].astype(str).str.len().max() or 0,
            )
            cap = _COL_MAX.get(col_name, 40)
            width = min(max_len + 2, cap)
            col_letter = ws.cell(1, col_idx).column_letter
            ws.column_dimensions[col_letter].width = width

        # Wrap text for long narrative columns
        from openpyxl.styles import Alignment
        _WRAP_COLS = {"plan", "sql_query", "llm_answer",
                      "steps_timeline", "filter_corrections",
                      "validation_issues", "result_data_json"}
        for col_idx, col_name in enumerate(out_df.columns, start=1):
            if col_name in _WRAP_COLS:
                for row_idx in range(2, len(out_df) + 2):
                    ws.cell(row_idx, col_idx).alignment = Alignment(wrap_text=True)

        # ── Result Data sheet: all rows from every query, stacked ─────────────
        data_rows: list[dict] = []
        for rec in results:
            raw_json = rec.get("result_data_json") or ""
            if not raw_json:
                continue
            try:
                parsed = json.loads(raw_json)
                if isinstance(parsed, list):
                    for r in parsed:
                        row = {"question_no": rec["question_no"],
                               "question":    rec["question"]}
                        if isinstance(r, dict):
                            row.update(r)
                        else:
                            row["value"] = r
                        data_rows.append(row)
            except Exception:
                pass

        if data_rows:
            data_df = pd.DataFrame(data_rows)
            data_df.to_excel(writer, index=False, sheet_name="Result Data")
            ws2 = writer.sheets["Result Data"]
            ws2.freeze_panes = "A2"
            # Auto-fit columns on the data sheet
            for col_idx, col_name in enumerate(data_df.columns, start=1):
                max_len = max(
                    len(str(col_name)),
                    data_df[col_name].astype(str).str.len().max() or 0,
                )
                ws2.column_dimensions[
                    ws2.cell(1, col_idx).column_letter
                ].width = min(max_len + 2, 50)

    tqdm.write(f"\n💾  Saved results → {out_path}")


# ─────────────────────────────────────────────────────────────────────────────
# Summary printer
# ─────────────────────────────────────────────────────────────────────────────

def _print_summary(results: List[Dict], total_wall: float) -> None:
    statuses   = [r.get("status", "error") for r in results]
    n_success  = statuses.count("success")
    n_error    = statuses.count("error")
    n_clarify  = statuses.count("clarification")
    n_non_data = statuses.count("non_data")

    times = [r["total_time_s"] for r in results if isinstance(r.get("total_time_s"), (int, float))]
    avg_t = sum(times) / len(times) if times else 0
    med_t = sorted(times)[len(times) // 2] if times else 0
    max_t = max(times) if times else 0

    tqdm.write("\n" + "═" * 62)
    tqdm.write("  BATCH SUMMARY")
    tqdm.write("═" * 62)
    tqdm.write(f"  Total          : {len(results)}")
    tqdm.write(f"  ✅ Success      : {n_success}")
    tqdm.write(f"  ❌ Error        : {n_error}")
    tqdm.write(f"  💬 Clarify/Non  : {n_clarify + n_non_data}")
    tqdm.write(f"  {'─'*40}")
    tqdm.write(f"  Wall-clock     : {total_wall:.1f} s  ({total_wall/60:.1f} min)")
    tqdm.write(f"  Throughput     : {len(results)/total_wall:.2f} q/s")
    tqdm.write(f"  Avg per q      : {avg_t:.2f} s")
    tqdm.write(f"  Median per q   : {med_t:.2f} s")
    tqdm.write(f"  Slowest q      : {max_t:.2f} s")
    if n_error:
        tqdm.write(f"\n  ⚠   First 3 errors:")
        for r in [r for r in results if r.get("status") == "error"][:3]:
            tqdm.write(f"       Q#{r['question_no']}: {str(r.get('error', ''))[:100]}")
    tqdm.write(f"  📋  Full logs  → {_log_path}")
    tqdm.write("═" * 62)


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> None:
    # ── Output path ───────────────────────────────────────────────────────────
    if _args.out:
        out_path = _args.out
    else:
        stem     = Path(_args.input).stem
        out_path = str(Path(_args.input).parent / f"{stem}_results_{_ts_str}.xlsx")

    # ── Load questions ────────────────────────────────────────────────────────
    try:
        pairs, _ = _load_questions(
            _args.input, _args.col, _args.limit, _args.retry_errors
        )
    except ValueError as exc:
        tqdm.write(f"❌  {exc}")
        sys.exit(1)

    if not pairs:
        tqdm.write("⚠   No questions to run.")
        sys.exit(0)

    # ── Warmup ────────────────────────────────────────────────────────────────
    if not _args.no_warmup:
        _warmup()

    # ── Progress bar setup ────────────────────────────────────────────────────
    _icon = {"success": "✅", "error": "❌", "clarification": "💬", "non_data": "💬"}
    counts = {"✅": 0, "❌": 0, "💬": 0}

    tqdm.write(
        f"\n🚀  {len(pairs)} questions | {_args.workers} worker(s) | output → {out_path}\n"
    )

    bar = tqdm(
        total=len(pairs),
        desc="Running",
        unit="q",
        dynamic_ncols=True,
        file=sys.stdout,
        bar_format="{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_fmt}] {postfix}",
        colour="cyan",
    )
    bar.set_postfix_str("✅ 0  ❌ 0  💬 0")

    # ── Parallel execution ────────────────────────────────────────────────────
    results: List[Dict] = [{}] * len(pairs)
    wall_start = time.time()
    done = 0

    with ThreadPoolExecutor(max_workers=_args.workers) as pool:
        future_to_idx = {
            pool.submit(_run_one, row_no, question): idx
            for idx, (row_no, question) in enumerate(pairs)
        }

        for future in as_completed(future_to_idx):
            idx = future_to_idx[future]
            try:
                row_result = future.result()
            except Exception as exc:
                row_no, question = pairs[idx]
                row_result = {
                    "question_no": row_no,
                    "question":    question,
                    "status":      "error",
                    "error":       f"Thread error: {exc}",
                    "total_time_s": round(time.time() - wall_start, 2),
                    **{k: "" for k in _OUTPUT_COLUMNS if k not in
                       ("question_no", "question", "status", "error", "total_time_s")},
                }

            results[idx] = row_result
            done += 1

            # Update progress bar
            icon = _icon.get(row_result.get("status", ""), "❌")
            counts[icon] = counts.get(icon, 0) + 1
            t_s  = row_result.get("total_time_s", "?")
            q_no = row_result.get("question_no", "?")
            bar.set_postfix_str(
                f"✅ {counts['✅']}  ❌ {counts['❌']}  💬 {counts['💬']}  "
                f"│ last Q#{q_no} {icon} {t_s}s"
            )
            bar.update(1)

            # Checkpoint every 50
            if done % 50 == 0:
                ckpt = out_path + ".checkpoint.xlsx"
                _save_results([r for r in results if r], ckpt)
                bar.write(f"💾  Checkpoint ({done}/{len(pairs)}) → {ckpt}")

    bar.close()

    # ── Final save ────────────────────────────────────────────────────────────
    total_wall = time.time() - wall_start
    results.sort(key=lambda r: r.get("question_no", 0))
    _save_results(results, out_path)
    _print_summary(results, total_wall)


if __name__ == "__main__":
    main()
